
#Client Settings
[client]
	#Whether player has to sneak to see additional info in waila
	waila_shift_for_info = false

	#Position of mode and/or item display on the screen - used by some of the tools and weapons.
	[client.hudPositions]
		#Position of Sojouner Staff HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		sojournerStaff = "TOP_RIGHT"
		#Position of Handgun HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		handgun = "TOP_RIGHT"
		#Position of Alkahestry Tome HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		alkahestryTome = "TOP_RIGHT"
		#Position of Destruction Catalyst HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		destructionCatalyst = "TOP_RIGHT"
		#Position of Ender Staff HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		enderStaff = "TOP_RIGHT"
		#Position of Ice Magus Rod HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		iceMagusRod = "TOP_RIGHT"
		#Position of Glacial Staff HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		glacialStaff = "TOP_RIGHT"
		#Position of Void Tear HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		voidTear = "TOP_RIGHT"
		#Position of Midas Touchstone HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		midasTouchstone = "TOP_RIGHT"
		#Position of Infernal Chalice HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		harvestRod = "TOP_RIGHT"
		#Position of Ender Staff HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		infernalChalice = "TOP_RIGHT"
		#Position of Hero Medallion HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		heroMedallion = "TOP_RIGHT"
		#Position of Pyromancer Staff HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		pyromancerStaff = "TOP_RIGHT"
		#Position of Rending Gale HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		rendingGale = "TOP_RIGHT"
		#Position of Mob Charm HUD
		#Allowed Values: BOTTOM_LEFT, LEFT, TOP_LEFT, TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
		mobCharm = "RIGHT"

